const marketLogoFiles: Record<string, string> = {
  BTC: 'btc.png',
  ETH: 'eth.png',
  USDT: 'usdt.png',
  BNB: 'bnb.png',
  USDC: 'usdc.png',
  DAI: 'dai.png',
  FDUSD: 'fdusd.png',
  XRP: 'xrp.png',
  SOL: 'sol.png',
  TRX: 'trx.png',
  HYPE: 'hype.jpg',
  ZEC: 'zec.png',
  DOGE: 'doge.png',
  LEO: 'leo.png',
  XMR: 'xmr.png',
  LINK: 'link.png',
  ADA: 'ada.png',
  XLM: 'xlm.jpg',
  BCH: 'bch.png',
  CANTON: 'canton.png',
  USD1: 'usd1.png',
  USDE: 'usde.png',
  LTC: 'ltc.png',
  TON: 'ton.png',
  HBAR: 'hbar.png',
  AVAX: 'avax.png',
  SUI: 'sui.png',
  SHIB: 'shib.png',
  UNI: 'uni.png',
  PYUSD: 'pyusd.png',
  CRO: 'cro.png',
  XAUT: 'xaut.png',
  TAO: 'tao.jpg',
  NEAR: 'near.jpg',
  M: 'm.png',
};

export function getMarketLogoFile(symbol: string) {
  return marketLogoFiles[symbol.toUpperCase()];
}